"""add price breakdown to sale items

Revision ID: 08e66921870a
Revises: 6faf478d1ba4
Create Date: 2025-12-15 21:40:07.546238

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "08e66921870a"
down_revision: str | Sequence[str] | None = "6faf478d1ba4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1️⃣ Add column as nullable
    op.add_column("sale_items", sa.Column("price_breakdown", sa.JSON(), nullable=True))

    # 2️⃣ Backfill existing rows with a safe placeholder
    op.execute(
        """
        UPDATE sale_items
        SET price_breakdown = json_build_object(
            'legacy', true
        )
        WHERE price_breakdown IS NULL;
        """
    )

    # 3️⃣ Enforce NOT NULL after backfill
    op.alter_column("sale_items", "price_breakdown", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sale_items", "price_breakdown")
    # ### end Alembic commands ###
