"""create items table

Revision ID: 2bf791e73e68
Revises: 791a5a21919f
Create Date: 2025-12-14 17:56:27.624823

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2bf791e73e68"
down_revision: str | Sequence[str] | None = "791a5a21919f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("shop_id", sa.UUID(), nullable=False),
        sa.Column("sku", sa.String(length=50), nullable=False),
        sa.Column("barcode", sa.String(length=100), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("metal", sa.String(length=50), nullable=False),
        sa.Column("purity", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("gross_weight", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column("net_weight", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column("making_charge", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("barcode"),
        sa.UniqueConstraint("sku"),
    )
    op.create_index(op.f("ix_items_shop_id"), "items", ["shop_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_items_shop_id"), table_name="items")
    op.drop_table("items")
    # ### end Alembic commands ###
