"""add customer details to sales

Revision ID: 62780bf78a42
Revises: d0daebab8b2b
Create Date: 2025-12-16 19:24:01.294769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62780bf78a42'
down_revision: Union[str, Sequence[str], None] = 'd0daebab8b2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sales", sa.Column("customer_name", sa.String(100), nullable=True))
    op.add_column("sales", sa.Column("customer_phone", sa.String(15), nullable=True))
    op.add_column("sales", sa.Column("customer_address", sa.String(255), nullable=True))
    op.add_column("sales", sa.Column("customer_state", sa.String(50), nullable=True))
    op.add_column("sales", sa.Column("customer_state_code", sa.String(5), nullable=True))

    # Backfill existing rows (safe defaults)
    op.execute(
        """
        UPDATE sales
        SET
            customer_name = 'N/A',
            customer_phone = 'N/A',
            customer_address = '',
            customer_state = 'West Bengal',
            customer_state_code = '19'
        WHERE customer_name IS NULL;
        """
    )

    # Enforce NOT NULL where required
    op.alter_column("sales", "customer_name", nullable=False)
    op.alter_column("sales", "customer_phone", nullable=False)
    op.alter_column("sales", "customer_state", nullable=False)
    op.alter_column("sales", "customer_state_code", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'customer_state_code')
    op.drop_column('sales', 'customer_state')
    op.drop_column('sales', 'customer_address')
    op.drop_column('sales', 'customer_phone')
    op.drop_column('sales', 'customer_name')
    op.drop_index(op.f('ix_items_category'), table_name='items')
    # ### end Alembic commands ###
