"""add barcode index

Revision ID: 6c1e90572ac2
Revises: f6a86ec71c76
Create Date: 2025-12-14 19:57:53.892353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c1e90572ac2'
down_revision: Union[str, Sequence[str], None] = 'f6a86ec71c76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('items_barcode_key'), 'items', type_='unique')
    op.create_index(op.f('ix_items_barcode'), 'items', ['barcode'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_barcode'), table_name='items')
    op.create_unique_constraint(op.f('items_barcode_key'), 'items', ['barcode'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
