"""add metal rates

Revision ID: 6faf478d1ba4
Revises: 7f984b48d5f2
Create Date: 2025-12-15 21:02:38.673657

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6faf478d1ba4"
down_revision: str | Sequence[str] | None = "7f984b48d5f2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "metal_rates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("metal", sa.String(length=20), nullable=False),
        sa.Column("purity", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("rate_per_gram", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "effective_from",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_metal_rates_effective_from"), "metal_rates", ["effective_from"], unique=False
    )
    op.create_index(op.f("ix_metal_rates_metal"), "metal_rates", ["metal"], unique=False)
    op.create_index(op.f("ix_metal_rates_purity"), "metal_rates", ["purity"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_metal_rates_purity"), table_name="metal_rates")
    op.drop_index(op.f("ix_metal_rates_metal"), table_name="metal_rates")
    op.drop_index(op.f("ix_metal_rates_effective_from"), table_name="metal_rates")
    op.drop_table("metal_rates")
    # ### end Alembic commands ###
