"""add quantity to sale_items

Revision ID: 751c6960983f
Revises: c85257382a45
Create Date: 2026-06-09 23:09:27.374542

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "751c6960983f"
down_revision: str | Sequence[str] | None = "c85257382a45"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_items_category"), "items", ["category"], unique=False)
    op.add_column(
        "sale_items", sa.Column("quantity", sa.Integer(), server_default="1", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sale_items", "quantity")
    op.drop_index(op.f("ix_items_category"), table_name="items")
    # ### end Alembic commands ###
