"""add change log

Revision ID: 7f984b48d5f2
Revises: 6c1e90572ac2
Create Date: 2025-12-15 15:45:25.861087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f984b48d5f2'
down_revision: Union[str, Sequence[str], None] = '6c1e90572ac2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.Column('entity', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_log_created_at'), 'change_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_change_log_entity_id'), 'change_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_change_log_shop_id'), 'change_log', ['shop_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_change_log_shop_id'), table_name='change_log')
    op.drop_index(op.f('ix_change_log_entity_id'), table_name='change_log')
    op.drop_index(op.f('ix_change_log_created_at'), table_name='change_log')
    op.drop_table('change_log')
    # ### end Alembic commands ###
