"""add item category

Revision ID: d0daebab8b2b
Revises: 08e66921870a
Create Date: 2025-12-16 18:51:00.522838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0daebab8b2b'
down_revision: Union[str, Sequence[str], None] = '08e66921870a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
        # 1️⃣ Add column as nullable
    op.add_column(
        "items",
        sa.Column("category", sa.String(length=20), nullable=True),
    )

    # 2️⃣ Backfill existing items as jewellery
    op.execute(
        """
        UPDATE items
        SET category = 'jewellery'
        WHERE category IS NULL;
        """
    )

    # 3️⃣ Enforce NOT NULL
    op.alter_column(
        "items",
        "category",
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_category'), table_name='items')
    op.drop_column('items', 'category')
    # ### end Alembic commands ###
